### ISSUE TITLE
Chef can leave map boundaries

### ISSUE THREAD

**Issue by laurenvictoriaa** [CrimsonLeaves/ENG1-Team20-Assessment2#1]
All chefs can leave map boundaries by exiting through the pizzabase tile or the oven tiles. 

Affects most recent version.

Can be fixed by updating collision detection to include the pizzabase tiles and the oven tiles.
<img width="598" alt="Screenshot 2023-03-03 at 12 41 40" src="https://user-images.githubusercontent.com/117826360/224308597-c361b787-42aa-452b-b7b8-b3d8fea3b3b5.png">
<img width="635" alt="Screenshot 2023-03-03 at 12 42 22" src="https://user-images.githubusercontent.com/117826360/224308669-28fe2273-2df0-4625-9a7b-d1bf621ae2aa.png">
<img width="634" alt="Screenshot 2023-03-10 at 11 43 15" src="https://user-images.githubusercontent.com/117826360/224309060-5df01e3b-4dc3-4854-bcf3-7c751e7c5a5e.png">

**Comment by Pangreor** [comment]
collison detection for the pizzabase and oven tiles has been added. chefs can no longer exit the map
