### ISSUE TITLE
Potato Station Test Failing

### ISSUE THREAD

**Issue by CrimsonLeaves** [CrimsonLeaves/ENG1-Team20-Assessment2#11]
When the CI runs, the test_PotatoStation fails due to a com.badlogic.gdx.utils.GdxRuntimeException. All of the other Ingredient Station tests pass. The test_PotatoStation passes on my laptop and is essentially a copy and paste of the other tests for the other stations so I'm not sure why this one in particular is failing.

**Comment by laurenvictoriaa** [comment]
Fixed - bug was a result of incorrect capitalisation on one of the potato textures. Good pickup from the testing :)
