### ISSUE TITLE
Tests Can't Create Instances

### ISSUE THREAD

**Issue by CrimsonLeaves** [CrimsonLeaves/ENG1-Team20-Assessment2#9]
When using the Headless Application to run tests, class instances using import com.badlogic.gdx e.g. World, Vector2 produce this error:
com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx-box2d64.dll'
at:
at com.badlogic.gdx.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:93)
To reproduce run:
Chef c = new Chef(new World(new Vector2(0, 0), true), 0, 0);
in a test.

**Comment by laurenvictoriaa** [comment]
Fixed - build.gradle needed updating with the Box2D dependencies to create Box2D worlds for the headless environment to run.
